#!/usr/bin/env python3
# -*- coding: utf-8 -*-
def change(vec, p1, p2):
        aux = vec[p1]
        vec[p1] = vec[p2]
        vec[p2] = aux
        
def app(vec,n):
    for i in range (0, len(vec)-1):
        for j in range (i+1, len(vec)):
                if vec[j] < vec[i]:
                        change(vec,i,j)
    return vec

def search(vec, x):
    y=0
    rvec=[]
    re=0
    if int(len(vec)/2) % 2 == 0:
        re=int(len(vec)/2)
    else:
        re=int(len(vec)/2)-1
    while y < len(vec):
        j=0
        if y == re:
            y=len(vec)
            j=len(vec)
            
        while j < len(vec):
            if vec[y]+vec[j] == x:
                rvec.append(str(vec[y])+','+str(vec[j]))
                j+=1
            else:
                j+=1
        y+=1
    return rvec
        

if __name__ == '__main__':
    input_vec=[1,9,5,0,20,-4,12,16,7]
    new_vec=app(input_vec,12)
    ds=search(new_vec,12)
    print(ds)